# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 696)
        font = QtGui.QFont()
        font.setFamily("Railway")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("@font-face{\n"
"    src:url(:/fonts/1x/Railway.otf)\n"
"}")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("#frame_2 {\n"
"    border-image: url(:/assets/1x/1x/Asset 3.png) 0 0 0 0 stretch stretch;\n"
"    background-color: transparent; /* Ensure the background does not affect child widgets */\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.outerFrame = QtWidgets.QFrame(self.frame_2)
        self.outerFrame.setMaximumSize(QtCore.QSize(873, 16777215))
        self.outerFrame.setStyleSheet("#outerFrame {\n"
"    border-image: url(:/assets/1x/1x/Asset 2.png) 0 0 0 0 stretch stretch;\n"
"    background-color: transparent; /* Ensure the background does not affect child widgets */\n"
"}\n"
"")
        self.outerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outerFrame.setObjectName("outerFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.outerFrame)
        self.verticalLayout_2.setContentsMargins(20, 15, 20, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_15 = QtWidgets.QFrame(self.outerFrame)
        self.frame_15.setStyleSheet("@font-face {\n"
"        font-family: \"Railway\";\n"
"        src: url(:/fonts/1x/Railway.otf);\n"
"    }\n"
"#comboBox{\n"
"    font-family:\"Railway\";\n"
"    font-size: 14pt;\n"
"}\n"
"#label_2{\n"
"    color: rgb(255, 255, 255);\n"
"    font-family:\"Railway\";\n"
"    font-size:10pt;\n"
"}\n"
"#label_3{\n"
"font-family:\"Railway\";\n"
"font-size:18pt;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_6.setContentsMargins(9, 9, 9, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_16)
        self.label_3.setStyleSheet("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_6.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.comboBox = QtWidgets.QComboBox(self.frame_17)
        self.comboBox.setMouseTracking(False)
        self.comboBox.setTabletTracking(False)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background: transparent;\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"    border-radius: 5px; /* Optional: Rounded corners */\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background: transparent;\n"
"    border: none;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(:/assets/1x/1x/icons8-arrow-down-100.png);\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: rgba(0, 0, 0, 0.7);\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.comboBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.comboBox.setMaxVisibleItems(10)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setMinimumContentsLength(5)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setFrame(False)
        self.comboBox.setModelColumn(0)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_11.addWidget(self.comboBox, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_6.addWidget(self.frame_17)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame = QtWidgets.QFrame(self.outerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("    @font-face {\n"
"        font-family: \"Railway\";\n"
"        src: url(:/fonts/1x/Railway.otf);\n"
"    }\n"
"QTabWidget{\n"
"    color: rgb(255, 255, 255);\n"
"    font-family:\"Railway\";\n"
"    font-size:13pt;\n"
"}\n"
"QTabWidget::pane {\n"
"        \n"
"        border: 0; /* Remove the border around the widget */\n"
"        background: transparent; /* Transparent background */\n"
"    }\n"
"    QTabBar::tab {\n"
"        background: transparent; /* Transparent tab background */\n"
"        color: white; /* Text color */\n"
"\n"
"    }\n"
"    QTabBar::tab:selected {\n"
"        background: rgba(255, 255, 255, 0.2); /* Semi-transparent for selected tab */\n"
"    }\n"
"    QTabBar::tab:hover {\n"
"        background: rgba(255, 255, 255, 0.1); /* Hover effect */\n"
"    }")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabWidgetPage2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_18 = QtWidgets.QFrame(self.tabWidgetPage2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy)
        self.frame_18.setMaximumSize(QtCore.QSize(617, 16777215))
        self.frame_18.setStyleSheet("    @font-face {\n"
"        font-family: \"Railway\";\n"
"        src: url(:/fonts/1x/Railway.otf);\n"
"    }\n"
"#frame_18{\n"
"    font-family:\"Railway\";\n"
"    background-color: transparent;\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_14.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_2.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.tabWidgetPage2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_19.sizePolicy().hasHeightForWidth())
        self.frame_19.setSizePolicy(sizePolicy)
        self.frame_19.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_19.setStyleSheet("    @font-face {\n"
"        font-family: \"Railway\";\n"
"        src: url(:/fonts/1x/Railway.otf);\n"
"    }\n"
"QFrame{\n"
"    \n"
"    font-size: 14pt;\n"
"    font-family: \"Railway\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#high_lbl{\n"
"    color: rgb(0, 159, 0);\n"
"    font-size: 15pt;font-family: \"Railway\";\n"
"}\n"
"#low_lbl{\n"
"    color: rgb(255, 0, 0);\n"
"    font-size: 15pt;font-family: \"Railway\";\n"
"}\n"
"#equal_lbl{\n"
"    color: rgb(255, 255, 127);\n"
"    font-size: 15pt;font-family: \"Railway\";\n"
"}\n"
"#new_lbl{\n"
"    color: rgb(0, 170, 255);\n"
"    font-size: 15pt;font-family: \"Railway\";\n"
"}")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.high = QtWidgets.QLabel(self.frame_19)
        self.high.setTextFormat(QtCore.Qt.AutoText)
        self.high.setScaledContents(False)
        self.high.setWordWrap(False)
        self.high.setObjectName("high")
        self.verticalLayout_13.addWidget(self.high, 0, QtCore.Qt.AlignVCenter)
        self.high_lbl = QtWidgets.QLabel(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.high_lbl.sizePolicy().hasHeightForWidth())
        self.high_lbl.setSizePolicy(sizePolicy)
        self.high_lbl.setScaledContents(True)
        self.high_lbl.setObjectName("high_lbl")
        self.verticalLayout_13.addWidget(self.high_lbl, 0, QtCore.Qt.AlignTop)
        self.low = QtWidgets.QLabel(self.frame_19)
        self.low.setObjectName("low")
        self.verticalLayout_13.addWidget(self.low, 0, QtCore.Qt.AlignVCenter)
        self.low_lbl = QtWidgets.QLabel(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.low_lbl.sizePolicy().hasHeightForWidth())
        self.low_lbl.setSizePolicy(sizePolicy)
        self.low_lbl.setScaledContents(True)
        self.low_lbl.setObjectName("low_lbl")
        self.verticalLayout_13.addWidget(self.low_lbl, 0, QtCore.Qt.AlignTop)
        self.equal = QtWidgets.QLabel(self.frame_19)
        self.equal.setStyleSheet("#frame_19{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 8pt \"Railway\";\n"
"}")
        self.equal.setObjectName("equal")
        self.verticalLayout_13.addWidget(self.equal)
        self.equal_lbl = QtWidgets.QLabel(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.equal_lbl.sizePolicy().hasHeightForWidth())
        self.equal_lbl.setSizePolicy(sizePolicy)
        self.equal_lbl.setScaledContents(True)
        self.equal_lbl.setObjectName("equal_lbl")
        self.verticalLayout_13.addWidget(self.equal_lbl, 0, QtCore.Qt.AlignTop)
        self.new_ = QtWidgets.QLabel(self.frame_19)
        self.new_.setObjectName("new_")
        self.verticalLayout_13.addWidget(self.new_)
        self.new_lbl = QtWidgets.QLabel(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_lbl.sizePolicy().hasHeightForWidth())
        self.new_lbl.setSizePolicy(sizePolicy)
        self.new_lbl.setScaledContents(True)
        self.new_lbl.setObjectName("new_lbl")
        self.verticalLayout_13.addWidget(self.new_lbl, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_19)
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tabWidgetPage1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_20 = QtWidgets.QFrame(self.tabWidgetPage1)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_20)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setStyleSheet("QTableWidget, QTableView {\n"
"    background-color: #2b2b2b;  /* Dark gray background */\n"
"    border: 2px solid #444444;  /* Border around the table */\n"
"    border-radius: 10px;  /* Rounded corners for the table */\n"
"    color: white;  /* White text */\n"
"    gridline-color: #555555;  /* Gridline color */\n"
"    font-size: 14px;  /* Font size */\n"
"    font-family: Arial, sans-serif;  /* Font family */\n"
"    selection-background-color: #454545;  /* Background color for selected cells */\n"
"    selection-color: white;  /* Text color for selected cells */\n"
"}\n"
"\n"
"QHeaderView {\n"
"    background-color: #3a3a3a;  /* Header background */\n"
"    border: none;  /* No border around headers */\n"
"    color: white;  /* Header text color */\n"
"    font-size: 15px;  /* Header font size */\n"
"    font-weight: bold;  /* Bold text for headers */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #3a3a3a;  /* Header section background */\n"
"    color: white;  /* Header section text color */\n"
"    padding: 5px;  /* Padding inside the header */\n"
"    border: 1px solid #444444;  /* Header border */\n"
"    border-radius: 5px;  /* Rounded edges for header sections */\n"
"    text-align: center;  /* Centered header text */\n"
"}\n"
"\n"
"QHeaderView::section:first {\n"
"    border-top-left-radius: 10px;  /* Rounded top-left corner of the first section */\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    border-top-right-radius: 10px;  /* Rounded top-right corner of the last section */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background-color: #2b2b2b;  /* Cell background color */\n"
"    padding: 5px;  /* Padding for cell content */\n"
"    border: none;  /* No border for cells */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #555555;  /* Background for selected cells */\n"
"    color: white;  /* Text color for selected cells */\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: #2b2b2b;  /* Scrollbar background */\n"
"    width: 10px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #555555;  /* Scrollbar handle */\n"
"    border-radius: 5px;  /* Rounded scrollbar handle */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(40)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.verticalLayout_16.addWidget(self.tableWidget)
        self.verticalLayout_15.addWidget(self.frame_20)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.verticalLayout_10.addWidget(self.tabWidget)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.outerFrame)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMaximumSize(QtCore.QSize(430, 16777215))
        self.frame_3.setStyleSheet("#frame_3{\n"
"    border-image: url(:/assets/1x/1x/Asset 5.png)     0 0 0 0 stretch stretch;\n"
"    background-color: transparent; /* Ensure the background does not affect child widgets */\n"
"}\n"
"    @font-face {\n"
"        font-family: \"Railway\";\n"
"        src: url(:/fonts/1x/Railway.otf);\n"
"    }\n"
"#label_4{\n"
"     font-family: \"Railway\";\n"
"    font-size:30px\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_12 = QtWidgets.QFrame(self.frame_3)
        self.frame_12.setMaximumSize(QtCore.QSize(20, 20))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_3.addWidget(self.frame_12, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_4.setStyleSheet("border-image: url(:/assets/1x/1x/Asset 4.png);\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setStyleSheet("    @font-face {\n"
"        font-family: \"Railway\";\n"
"        src: url(:/fonts/1x/Railway.otf);\n"
"    }\n"
"#date_label1{\n"
"     font-family: \"Railway\";\n"
"    font-size:12px\n"
"}\n"
"#label_5{\n"
"    font-family:\"Railway\";\n"
"    font-size:12px;\n"
"}\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5, 0, QtCore.Qt.AlignLeft)
        self.date_label1 = QtWidgets.QLabel(self.frame_10)
        self.date_label1.setStyleSheet("")
        self.date_label1.setObjectName("date_label1")
        self.horizontalLayout_4.addWidget(self.date_label1, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_6.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setStyleSheet("    @font-face {\n"
"        font-family: \"Railway\";\n"
"        src: url(:/fonts/1x/Railway.otf);\n"
"    }\n"
"#sale_label{\n"
"     font-family: \"Railway\";\n"
"    font-size:30px\n"
"}\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.sale_label = QtWidgets.QLabel(self.frame_9)
        self.sale_label.setStyleSheet("")
        self.sale_label.setScaledContents(True)
        self.sale_label.setObjectName("sale_label")
        self.verticalLayout_7.addWidget(self.sale_label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addWidget(self.frame_9)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_5.setStyleSheet("\n"
"#frame_5{\n"
"    border-image: url(:/assets/1x/1x/Asset 4.png) 0 0 0 0 stretch stretch;\n"
"    background-color: transparent; /* Ensure the background does not affect child widgets */\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setStyleSheet("    @font-face {\n"
"        font-family: \"Railway\";\n"
"        src: url(:/fonts/1x/Railway.otf);\n"
"    }\n"
"#date_label_2{\n"
"     font-family: \"Railway\";\n"
"    font-size:12px\n"
"}\n"
"#label{\n"
"    font-family:\"Railway\";\n"
"    font-size:12px;\n"
"}\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_8)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.date_label_2 = QtWidgets.QLabel(self.frame_8)
        self.date_label_2.setStyleSheet("")
        self.date_label_2.setObjectName("date_label_2")
        self.horizontalLayout_3.addWidget(self.date_label_2, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setStyleSheet("    @font-face {\n"
"        font-family: \"Railway\";\n"
"        src: url(:/fonts/1x/Railway.otf);\n"
"    }\n"
"#buy_label{\n"
"    font-family:\"Railway\";\n"
"    font-size:30px;\n"
"}\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.buy_label = QtWidgets.QLabel(self.frame_7)
        self.buy_label.setStyleSheet("")
        self.buy_label.setScaledContents(True)
        self.buy_label.setObjectName("buy_label")
        self.verticalLayout_5.addWidget(self.buy_label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_14 = QtWidgets.QFrame(self.frame_3)
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 43))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_3.addWidget(self.frame_14)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_13 = QtWidgets.QFrame(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.frame_13.setFont(font)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.inputtext = QtWidgets.QLineEdit(self.frame_13)
        self.inputtext.setMinimumSize(QtCore.QSize(0, 0))
        self.inputtext.setMaximumSize(QtCore.QSize(16777215, 45))
        self.inputtext.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.inputtext.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inputtext.setStyleSheet("    @font-face {\n"
"        font-family: \"Railway\";\n"
"        src: url(:/fonts/1x/Railway.otf);\n"
"    }\n"
"#inputtext{\n"
"font-family: \"Railway\";\n"
"font-size:15px;\n"
"border-image: url(:/assets/1x/1x/Asset 8.png);}\n"
"")
        self.inputtext.setInputMask("")
        self.inputtext.setText("")
        self.inputtext.setAlignment(QtCore.Qt.AlignCenter)
        self.inputtext.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.inputtext.setClearButtonEnabled(True)
        self.inputtext.setObjectName("inputtext")
        self.verticalLayout_9.addWidget(self.inputtext)
        self.frame_11 = QtWidgets.QFrame(self.frame_13)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.search_button = QtWidgets.QPushButton(self.frame_11)
        self.search_button.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Railway")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.search_button.setFont(font)
        self.search_button.setStyleSheet("\n"
"    @font-face {\n"
"        font-family: \"Railway\";\n"
"        src: url(:/fonts/1x/Railway.otf);\n"
"    }\n"
"#search_button{\n"
"font-family: \"Railway\";\n"
"font-size:15px;\n"
"border-image: url(:/assets/1x/1x/Asset 6.png);}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/1x/1x/Asset 7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_5.addWidget(self.search_button)
        self.verticalLayout_9.addWidget(self.frame_11)
        self.verticalLayout_8.addWidget(self.frame_13)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout_12.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1044, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Dashboard"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Overall of nov_aug"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Shares Gained"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Shares Reduced"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Unchanged"))
        self.comboBox.setItemText(4, _translate("MainWindow", "New added"))
        self.high.setText(_translate("MainWindow", "Shares Amount Gained"))
        self.high_lbl.setText(_translate("MainWindow", "+154985232"))
        self.low.setText(_translate("MainWindow", "Shares Amount Reduced"))
        self.low_lbl.setText(_translate("MainWindow", "-356565363"))
        self.equal.setText(_translate("MainWindow", "Unchanged Shares "))
        self.equal_lbl.setText(_translate("MainWindow", "=2548989"))
        self.new_.setText(_translate("MainWindow", "New Shares Added"))
        self.new_lbl.setText(_translate("MainWindow", "2545"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("MainWindow", "Chart"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("MainWindow", "Table"))
        self.label_4.setText(_translate("MainWindow", "      Data Overview"))
        self.label_5.setText(_translate("MainWindow", "November Shares Amount"))
        self.date_label1.setText(_translate("MainWindow", "08/11/2024"))
        self.sale_label.setText(_translate("MainWindow", "0.00"))
        self.label.setText(_translate("MainWindow", "August Shares Amount"))
        self.date_label_2.setText(_translate("MainWindow", "02/08/2024"))
        self.buy_label.setText(_translate("MainWindow", "0.00"))
        self.inputtext.setPlaceholderText(_translate("MainWindow", "Name of isuuer"))
        self.search_button.setText(_translate("MainWindow", "Search"))
from . import resource_rc
